### ISSUE TITLE
jq: command not found

### ISSUE THREAD

**Issue by soenkehahn** [jfroche/flake-fzf#1]
Running this on a system where `jq` is not installed, I get this:

```
$ nix run github:jfroche/flake-fzf
++ nix-instantiate --eval --expr builtins.currentSystem --json
++ jq -r
/nix/store/a17x57gd1wb37n8zjqsdjs2n0isn2zwd-flake-fzf.sh: line 4: jq: command not found
+ system=
```

I think a working version of `jq` should be made available to the script.

**Comment by jfroche** [comment]
Oh, this should have been closed by https://github.com/jfroche/flake-fzf/commit/9bc17239922fa25edcdb5ce0c9b9677e3b29b8ae
Thank you for taking the time to write about it !
